apiVersion: v1
kind: ConfigMap
metadata:
  name: kraftwerk-config-dv
  namespace: default
data:
  fr.insee.postcollecte.files: C:\\Users\\QDIBYS\\Documents\\Kraftwerk_folder
  logging.level.root: INFO
  logging.level.fr.insee.kraftwerk: INFO
  logging.file.name: C:\\Users\\QDIBYS\\Documents\\Kraftwerk_folder\\log\\kraftwerk.log
  logging.pattern.rolling-file-name: C:\\Users\\QDIBYS\\Documents\\Kraftwerk_folder\\log\\kraftwerk-%d{yyyy-MM-dd}.%i.log
  fr.insee.postcollecte.genesis.api.url: http://api-reponses-enquetes.dev.kube.insee.fr

  server.port: 8080