apiVersion: apps/v1
kind: Deployment
metadata:
  name: kraftwerk-deployment
spec:
  replicas: 1 #TODO Set to 3 with helm
  selector:
    matchLabels:
      app: kraftwerk
  template:
    metadata:
      labels:
        app: kraftwerk
    spec:
      automountServiceAccountToken: false
      containers:
        - name: kraftwerk-container
          image: gitlab-registry.insee.fr:443/sic/traitements-post-collecte/deployment/kraftwerk-deployment:latest
          imagePullPolicy: Always
          securityContext:
            allowPrivilegeEscalation: false
            capabilities:
              drop:
                - ALL
            readOnlyRootFilesystem: true
            runAsNonRoot: true
          resources:
            limits:
              memory: "600Mi"
              cpu: "500m"
            requests:
              memory: "1Mi"
              cpu: "10m"
          ports:
            - containerPort: 8080
          livenessProbe:
            failureThreshold: 3
            httpGet:
              path: /actuator/health/liveness
              port: 8080
              scheme: HTTP
            initialDelaySeconds: 45
            periodSeconds: 60
            successThreshold: 1
            timeoutSeconds: 1
          readinessProbe:
            failureThreshold: 3
            httpGet:
              path: /actuator/health/readiness
              port: 8080
              scheme: HTTP
            initialDelaySeconds: 45
            periodSeconds: 60
            successThreshold: 1
            timeoutSeconds: 1
          envFrom:
            - configMapRef:
                name: kraftwerk-config-dv
          volumeMounts:
            - mountPath: /tmp/
              name: kraftwerk-temp-volume
            - mountPath: /storage/
              name: kraftwerk-volume
      volumes:
        - name: kraftwerk-temp-volume
          emptyDir : {}
        - name: kraftwerk-volume
          persistentVolumeClaim:
            claimName: kraftwerk-pvc