apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: kraftwerk-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
      #TODO reclaimPolicy en recycle (pour éviter la suppression du PV)