name: Create tag and release

on:
  push:
    branches:
      - main
  pull_request:
    branches: [ "main" ]
jobs:
  check-version:
    runs-on: ubuntu-latest
    outputs:
      release-version: ${{ steps.version-step.outputs.version }}
      release-tag: ${{ steps.version-step.outputs.newTag }}
    steps:
      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'

      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Get source version
        id: version-step
        run: echo "version=$(mvn -f pom.xml help:evaluate -Dexpression=project.version -q -DforceStdout)" >> $GITHUB_OUTPUT
             echo "newTag=v$(mvn -f pom.xml help:evaluate -Dexpression=project.version -q -DforceStdout)" >> $GITHUB_OUTPUT

      - name: Print source version
        run: echo ${{ steps.version-step.outputs.version }}

      - uses: mukunku/tag-exists-action@v1.6.0
        name: Check tag existence
        id: check-tag-exists
        with:
          tag: ${{ steps.version-step.outputs.newTag }}

      - name: Tag verification
        id: check-tag
        run: |
          if [[ "${{ steps.check-tag-exists.outputs.exists }}" == "true" ]]; then
            echo "Nothing to tag/release, the tag ${{ steps.version-step.outputs.version }} already exists"
            exit 1
          fi

          if ! [[ "${{ steps.version-step.outputs.version }}" =~ ^v[0-9]+.[0-9]+.[0-9]+$ ]]; then
            echo "Nothing to tag/release, the tag ${{ steps.version-step.outputs.version }} is not in correct format X.Y.Z"
            exit 1
          fi

  create-release:
    needs: [ check-version ]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ github.ref }}
          fetch-depth: 0

      - name: Get previous final release tag
        id: previousTag
        run: echo "previousTag=$(git --no-pager tag --sort=creatordate --merged ${{ github.ref_name }} | grep "^v[0-9]\+\.[0-9]\+\.[0-9]\+$" | tail -1)" >> $GITHUB_OUTPUT

      - name: Extract content between titles
        id: changeLogContent
        run: |
          FILE_PATH='CHANGELOG.md'
          echo "TITLE1=$(sed -n '/^# /p' $FILE_PATH | awk 'NR==1')" >> $GITHUB_OUTPUT
          echo "TITLE2=$(sed -n '/^# /p' $FILE_PATH | awk 'NR==2')" >> $GITHUB_OUTPUT
          echo "changes=$(sed -n "/${TITLE1}/,/${TITLE2}/{/${TITLE1}/b;/${TITLE2}/b;p;} $FILE_PATH )" >> $GITHUB_OUTPUT

      - uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ needs.check-version.outputs.release-tag }}
          target_commitish: ${{ github.head_ref || github.ref }}
          name: ${{  {steps.changeLogContent.outputs.TITLE1 }} 
          body: ${{steps.changeLogContent.outputs.changes}}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
