name: Version Update Action

on:
  pull_request:
    branches:
      - main
    types: [labeled]

jobs:
  update-pom-version:
    runs-on: ubuntu-latest
    if: >
      contains(github.event.pull_request.labels.*.name, 'Version Update - Staging') ||
      contains(github.event.pull_request.labels.*.name, 'Version Update - Prod')
    steps:
      - name: Checkout PR branch
        uses: actions/checkout@v4
        with:
          ref: ${{ github.head_ref }}
      
      - name: Get Short SHA
        id: sha
        run: echo "sha_short=$(echo $GITHUB_SHA | cut -c1-7)" >> $GITHUB_OUTPUT

      - name: Extract version from PR title
        id: extract_version
        run: |
          TITLE_VERSION=$(echo '${{ github.event.pull_request.title }}' | grep -oE '[0-9]+\.[0-9]+\.[0-9]+' || true)
          if [ -z "$TITLE_VERSION" ]; then
            echo "No version in PR title. Will increment patch from current pom version."
          else
            echo "Detected version from PR title: $TITLE_VERSION"
          fi
          echo "title_version=$TITLE_VERSION" >> $GITHUB_OUTPUT

      - name: Get current version from pom.xml
        id: current_version
        run: |
          CURRENT_VERSION=$(mvn help:evaluate -Dexpression=project.version -q -DforceStdout)
          echo "Current POM version: $CURRENT_VERSION"
          echo "current_version=$CURRENT_VERSION" >> $GITHUB_OUTPUT

      - name: Determine base version
        id: base_version
        run: |
          if [ -n "${{ steps.extract_version.outputs.title_version }}" ]; then
            BASE_VERSION="${{ steps.extract_version.outputs.title_version }}"
          else
            CUR="${{ steps.current_version.outputs.current_version }}"
            IFS='.' read -r MAJOR MINOR PATCH <<< "$CUR"
            PATCH=$((PATCH + 1))
            BASE_VERSION="$MAJOR.$MINOR.$PATCH"
            echo "Auto-incremented patch version: $BASE_VERSION"
          fi
          echo "base_version=$BASE_VE
